### ISSUE TITLE
Launch Calcite Parse Locally

### ISSUE THREAD

**Issue by seliang** [sql-machine-learning/sqlflow#1091]
**Is your feature request related to a problem? Please describe.**
Calcite Parser is written in Java can't be called directly from Go. So we should either launch it remotely as a service or locally in JVM.

**Describe the solution you'd like**
The plan would be launching this parser locally to avoid more burden to serve a new service. To achieve local deployment, https://golang.org/pkg/os/exec/ will be used to init Calcite Parser and the input & output will be transferred through https://golang.org/pkg/os/exec/#Cmd.StdinPipe

**Comment by tonyyang-svail** [comment]
Hi @seliang, thanks for filing this issue.

Yes, launching Calcite/HiveQL parser locally can avoid setting up an additional gRPC server during the deployment. Also, since there is no downstream call for the parser, wrapping the parser as a service might be overkill.

I am wondering if you can contribute to this.

You can find our current gRPC implementation at `parser/remote`, and there is a nice README describing the logic of the code. For sample test cases, you can refer to https://github.com/sql-machine-learning/sqlflow/pull/1046, where I have been experimenting with the same logic with TiDB parser. I can help with the code review and integrating the tests into our CI.

In terms of the command line API, I am thinking the command takes a string and prints the result in JSON format.

Please let me know what you think. :)

**Comment by tonyyang-svail** [comment]
Fixed by https://github.com/sql-machine-learning/sqlflow/pull/1140.
