### ISSUE TITLE
Slight reorg TensorFlow submitter template

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/sqlflow#1098]
Are the following two source files example TensorFlow submitter programs?

- https://github.com/sql-machine-learning/sqlflow/blob/develop/python/sqlflow_submitter/tensorflow/estimator_train_pred.py
- https://github.com/sql-machine-learning/sqlflow/blob/develop/python/sqlflow_submitter/tensorflow/keras_train_pred.py

If so, how about we rename them into `estimator_example.py` and `keras_example.py`?

**Comment by typhoonzero** [comment]
@wangkuiyi  these files are used by unit tests. The reason why I did this is here: https://github.com/sql-machine-learning/sqlflow/blob/develop/python/sqlflow_submitter/tensorflow/train_predict_test.py#L19. And, these files could not be named `xxx_test.py` because it will be recognized as test files and ran by the test scripts.
