### ISSUE TITLE
Wrongly recognize database and table with same name in predict clause

### ISSUE THREAD

**Issue by BlackPoint-CX** [sql-machine-learning/sqlflow#1129]
**Description**
When user has named one table by the same name of database, SQLFlow cannot distinguish them in predict clause.

**Reproduction Steps**
```
...
PREDICT database_test.iris_predict.class
...
```
will fail when there is a table named `database_test` in database `database_test`

It can be temporarily solved by remove the table name in predict clause like `PREDICT iris_predict.class`.

**Comment by Yancey0623** [comment]
Hi @BlackPoint-CX , I think the reason is that the Hive `DESCRIBE` syntax is `DESCRIBE (db.)table(.col)`, for a specified case: the user-typed table name is `describe mydb.mytable`, but `mydb` is also a table name in the default database. Hive would confuse `mydb` as a table name and `mytable` as a column.
