### ISSUE TITLE
github.com/sql-machine-learning/sqlflow/server/proto.RegisterSQLFlowServer is not defined

### ISSUE THREAD

**Issue by gxf1986** [sql-machine-learning/sqlflow#1242]
**Description**
I download the sqlflow-release-0.1 branch. I try to build server from source code without docker.
When i run go generate ./... command, it could transfer server/proto/sqlflow.proto into sqlflow.pb.go. However the proto.RegisterSQLFlowServer can not be resolved in cmd/sqlflowserver/main.go. I have look up the sqlflow.pb.go file, there is no RegisterSQLFlowServer method defined. please help.

**Comment by typhoonzero** [comment]
What's the version of protobuf (protoc) installed on your machine, and what version is your Go compiler?

**Comment by tonyyang-svail** [comment]
@typhoonzero shall we make generated proto files part of our source files? I received similar complaints from @samplise when he is trying out `pkg/sql/codegen` while finding it hard to do `go generate ./...`.

**Comment by typhoonzero** [comment]
@tonyyang-svail I don't think so. We only provide a docker container as the build environment, in case that the dependencies are updated, e.g. we must include JDK 1.8 to compile the parser. We recommend users to compile SQLFlow binaries using this Docker image so that it can be ported to any environment.

So, @gxf1986 can you please use the Docker image `sqlflow/sqlflow` to build the binaries and copy them into you runtime environment for deployment? It's the best way to compile SQLFlow.

**Comment by wangkuiyi** [comment]
I second @typhoonzero .

Sorry @gxf1986 we don't have enough manpower to support native build. Please use docker. Thanks.

**Comment by gxf1986** [comment]
Thanks for your reply
