### ISSUE TITLE
does sqlflow support hive2

### ISSUE THREAD

**Issue by JBjumper** [sql-machine-learning/sqlflow#1246]
**Is your feature request related to a problem? Please describe.**
does sqlflow support hive2?
if support ,how to connect to hive2?

**Describe the solution you'd like**

I failed to connect hive2 in the following way：
SQLFLOW_DATASOURCE='hive://root:root@hostname:10010/iris'

it says failed to ping database.

**Describe alternatives (optional)**

**Additional Notes**

**Comment by tonyyang-svail** [comment]
Hi @JBjumper, what is the Hive version you are using? the Hive version we used in our CI is `Hive 2.3.2`, SQLFlow should work with Hive 2.x.

"Failed to ping database" is usually due to the incorrect server configuration or the `SQLFLOW_DATASOURCE`. There are several ways to debug this. As the first step, I would suggest trying to connect your Hive server by writing a Python script using `impyla==0.16.0`. You can find an example [here](https://github.com/cloudera/impyla#usage). If you can't connect your Hive server using impyla, then it is likely additional authentication configuration is needed.
