### ISSUE TITLE
An error reported when the column is not "*" in  validation.select 

### ISSUE THREAD

**Issue by Echo9573** [sql-machine-learning/sqlflow#1270]
some error will be reported when the column is not "*" in  the `validation.select` , the detail is shown as following figure:
![image](https://user-images.githubusercontent.com/24820352/69701458-ef099200-1127-11ea-8ed4-24309e73a788.png)

**Comment by typhoonzero** [comment]
@Echo9573 can you please try adding fields in the SELECT clause like:

```sql
SELECT crim,zn,indus,chas,nox,rm,age,medv FROM boston.train
TO TRAIN ...
```

**Comment by typhoonzero** [comment]
Seems using `SELECT crim,zn,indus,chas,nox,rm,age,medv FROM boston.train TO TRAIN...` can solve this problem. And this leads to another enhancement:

We need to log that which columns are used for training in the notebook so that we would not confuse about what fields are actually used by the training.

**Comment by Echo9573** [comment]
> Seems using `SELECT crim,zn,indus,chas,nox,rm,age,medv FROM boston.train TO TRAIN...` can solve this problem. And this leads to another enhancement:
> 
> We need to log that which columns are used for training in the notebook so that we would not confuse about what fields are actually used by the training.

Thanks for your reply! Yes, it looks more friendly to users.
