### ISSUE TITLE
The currently syntax rules mistakenly enables TO TRAIN without SELECT

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/sqlflow#1418]
The current syntax rules in sql.y are as follows:

https://github.com/sql-machine-learning/sqlflow/blob/d0db43bdb7fb74298b7816915a0f5d1a8b934145/pkg/sql/sql.y#L188-L207

These rules accept the TO TRAIN/PREDICT/EXPLAIN clauses without the prefixed SELECT statement. This is not our design.

**Comment by typhoonzero** [comment]
This is what we are expecting for now, and will only accept SQLs start from `TO TRAIN ...` later, because:

1. we use the third-party parser to split standard SQL and extended SQL, if the statement is extended SQL, we will pass the extended part from `TO TRAIN` to sql.y and check the grammar of the standard SQL.
2. for backward compatibility, we kept accepting the full extended SQL and it's currently not used currently, will be removed later .
