### ISSUE TITLE
GoYacc: improve syntax error messages

### ISSUE THREAD

**Issue by tonyyang-svail** [sql-machine-learning/sqlflow#170]
The error message in parser can be improved.

1. One good read: https://research.swtch.com/yyerror

**Comment by wangkuiyi** [comment]
Thank you @tonyyang-svail for recommending the blog post by Ross Cox. I read it. 

This post compares two approaches to writing a parser: (1) by-hand and using recursion descending, and (2) using a parser generator like yacc/goyacc/bison.  The former is known better at generating meaningful suggestions for syntax errors.  Russ Cox showed that by adding a post-processing step, he enabled the bison-generated parsers of the Go compiler to generate meaningful suggestions.

However, when I dig into the Go codebase, I realized that after the above work, Go authors finally turned completely from the bison-generated parser to hand-written parser, in which, I found the meaningful suggestions mentioned in the above blog post, but in another form.

After reading this, I realized that parser generators are good for a project in its early stage.  After the maturation of the project, the author can rewrite the parser by-hand to make it generate meaningful error messages.

**Comment by wangkuiyi** [comment]
A recent [bug report](https://github.com/sql-machine-learning/sqlflow/issues/2165#issue-608229999) presents a case that refers back to this very old issue.  To make the discussion self-contained, let me copy the case from @Yancey1989 to here:

When users input the following SQLFlow program

```
SELECT * FROM alifin_jtest_dev.sqlflow_titanic_train
TO TO TRAIN DNNClassifier WITH
model.hidden_units=[200, 200, 200]
model.no_exits=abc,
LABEL survived
INTO my_titanic_model;
Error Message:
```

She would get the following error message

```
runSQLProgram error: syntax error: at (3 ~ 5)-th runes near "TO TRAIN D"
```

However, the above information is not very meaningful. What she wants might be the following.

```
syntax error: ... TO TO TRAIN ..."
```

Unfortunately, given what I learned and summarized in https://github.com/sql-machine-learning/sqlflow/issues/170#issuecomment-620871377, I am afraid that at the right moment, we still need to stick on the goyacc-generated parser.  Therefore, we could either use Ross Cox's method, or, we give it a quick fix.  Let us do a quick fix.

I think Ross Cox's method is innovative and interesting.  However, given that the later choice of Go Authors is a hand-written parser, our next step might be to rewrite our parser by hand, other than implementing Ross Cox's method.

**Comment by wangkuiyi** [comment]
As we cannot make the syntax error message more meaningful, let us try to make it less redundant.

Here is an example of the current error message:

```
runSQLProgram error: syntax error: at (3 ~ 5)-th runes near "TO TRAIN D"
```

- The caller `runSQLProgram error:` is not meaningful. It only tells the name of the function that processed the SQLFlow program.  However, users don't care about which function processed their program.

- The `syntax error:` is from goyacc, as shown in 

  https://github.com/sql-machine-learning/sqlflow/blob/388a9cd6f25275d209c28afd786541719d0503ae/pkg/parser/lexer.go#L47-L50

- the part `at (3 ~ 5)-th runes` doesn't make sense to the users.  The position starts from the end of the SELECT statement due to the collaborative parsing algorithm, which is out of users' interest.

Let me 

- remove the position,
- change `near` to `before or near`, and
- add a URL pointing to SQLFlow syntax guide https://sqlflow.org/sqlflow/doc/language_guide
