### ISSUE TITLE
SELECT * FROM {table_name}, the data is not in table web view in Dataworks.

### ISSUE THREAD

**Issue by brightcoder01** [sql-machine-learning/sqlflow#1736]
**Description**
Execute the standard SQL in MaxCompute.
```SQL
SELECT * FROM table_xxx
```
The data should be in table web view as the standard ODPS SQL execution result. 
Currently the selected result data is shown in the log. It's not user friendly.

**Environment (Please complete the following information):**
 - OS:
 - Browser:
 - Version:

**Additional Notes**

**Comment by wangkuiyi** [comment]
@brightcoder01 Do you mean the SELECT result does not show up in a table view of Dataworks? In my mind, MaxCompute is a database system and a computing platform, which doesn't have any table view; However, Dataworks is the GUI, which provides the table view.

**Comment by brightcoder01** [comment]
> @brightcoder01 Do you mean the SELECT result does not show up in a table view of Dataworks? In my mind, MaxCompute is a database system and a computing platform, which doesn't have any table view; However, Dataworks is the GUI, which provides the table view.

Yes, you are right. The result is not shown as a table view in the GUI. It's Dataworks.

**Comment by typhoonzero** [comment]
Thanks for reporting, this is one enhancement we are already planning to do in the next release. 

Currently, since every SQL program will be executed as one workflow on kubernetes Cluster, we can only get the logs from the pods. Yet it's possible to log the table data as some serialized format ( e.g. protobuf or JSON) we can convert the log to some table object and pass it to Dataworks.

**Comment by tonyyang-svail** [comment]
This feature is supported at https://github.com/sql-machine-learning/sqlflow/issues/1873.
