### ISSUE TITLE
Proposal: Make repl call SQLFlow server

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/sqlflow#1744]
Currently, the binary repl call [`func RunSQLProgram`](https://github.com/sql-machine-learning/sqlflow/blob/5ab490f740decbb8c3f293461c7920d5ef2f8979/pkg/sql/executor_ir.go#L52) locally.

I propose to 

1. Rename repl into sqlflow.
1. Make repl call SQLFlow server, just like mysql calls MySQL server.
1. Move part of `RunSQLProgram` in `executor_ir.go` to `pkg/server` and the rest to `pkg/step/executor/`.  The former part calls the later part.

BTW, we need `cmd/step`, which calls `pkg/step/executor/` and is called by the generated workflow to run each step, as explained in https://github.com/sql-machine-learning/sqlflow/issues/1746.

A side-effect of this proposal is to reduce and finally remove the file `execute_ir.go`, as the IR is not executable -- it is the submitter program generated from the IR which is executable.

**Comment by shendiaomo** [comment]
> Currently, the binary repl call [`func RunSQLProgram`](https://github.com/sql-machine-learning/sqlflow/blob/5ab490f740decbb8c3f293461c7920d5ef2f8979/pkg/sql/executor_ir.go#L52) locally.
> 
> I propose to
> 
> 1. Rename repl into sqlflow.
> 2. Make repl call SQLFlow server, just like mysql calls MySQL server.

Maybe we can consider moving REPL to a standalone repo? So users can build and use REPL without Docker.

**Comment by typhoonzero** [comment]
Note that when we run `pip install pysqlflow`, it will install a command `sqlflow` on the current machine. This `sqlflow` command is implemented using Python and can connect to the sqlflow server to run SQL programs.

I agree with rename repl into sqlflow and it should act as a sqlflow client since it provides better console features. Then we must remove the Python `sqlflow` command.
