### ISSUE TITLE
Failed:Run SQLFlow Command-line Tool

### ISSUE THREAD

**Issue by Kelang-Tian** [sql-machine-learning/sqlflow#2543]
**Description**
Unable to run program according to documentation.
[https://github.com/sql-machine-learning/sqlflow/blob/develop/doc/run/cli.md](url)
-Because `sqlflow` here is a binary file, so I don't know how to deal with the error.
-In the docker of the `sqlflowserver` name, the error is in the command `/start.sh sqlflow-server-with-dataset`, and the `/start.sh` script has two sentences:` echo "Start SQLFlow server ..."` and `sqlflowserver`. 

**Reproduction Steps**
Run  failed `sqlflow --sqlflow_server="$(docker port sqlflowserver 50051)" \
     --datasource="mysql://root:root@tcp(localhost:3306)/?maxAllowedPacket=0"`

**Expected Behavior**
What you expected to happen.

**Screenshots**
terminal display
> Can't connect to mysql://root:root@tcp(localhost:3306)/?maxAllowedPacket=0: rpc error: code = Unknown desc = create DB failed: failed to ping database: dial tcp 127.0.0.1:3306: connect: connection refused

**Comment by AayushTyagi1** [comment]
Same issue with me too. Failed to correct to localhost.

**Comment by wangkuiyi** [comment]
Thanks for reporting the issue @AayushTyagi1 and @Kelang-Tian . @lhw362950217 please take a look at it. Thanks!

**Comment by lhw362950217** [comment]
hi, @AayushTyagi1 , this problem has some reasons. In a word, we recommend you to use our [playground](https://github.com/sql-machine-learning/playground) instead of the docker image.

As to the problem itself. It mainly because we have split our docker image into several small ones. So there is no mysql at `localhost:3306`. It's a bit complicated to start all the images by hand, so we supplied a playground in which you can get a better experience. Also, I will fix the doc soon, thanks!

**Comment by Kelang-Tian** [comment]
> hi, @AayushTyagi1 , this problem has some reasons. In a word, we recommend you to use our [playground](https://github.com/sql-machine-learning/playground) instead of the docker image.
> 
> As to the problem itself. It mainly because we have split our docker image into several small ones. So there is no mysql at `localhost:3306`. It's a bit complicated to start all the images by hand, so we supplied a playground in which you can get a better experience. Also, I will fix the doc soon, thanks!

Thanks！You deal with problems quickly.
