### ISSUE TITLE
The step  `git clone` is missing from the setup mysql.

### ISSUE THREAD

**Issue by llxxxll** [sql-machine-learning/sqlflow#264]
https://github.com/sql-machine-learning/sqlflow/blob/develop/doc/quickstart.md#setup

**Comment by wangkuiyi** [comment]
I think this is because users now don't need to clone the source code and build SQLFlow. Instead, @tonyyang-svail configured Travis CI to build SQLFlow and release Docker images every time we merge a PR into the develop branch:

https://github.com/sql-machine-learning/sqlflow/blob/9ff2f085f656d18f0952fa8438135cf3f12173a2/.travis.yml#L32-L37

The Quick Start document now explains how to run Docker images built by Travis CI.
