### ISSUE TITLE
Does SQLFlow have a plan to support the Windows platform.

### ISSUE THREAD

**Issue by llxxxll** [sql-machine-learning/sqlflow#276]
run  `docker pull sqlflow/sqlflow:latest`  , 
feedback `image operating system "linux" cannot be used on this platform`

**Information**
- Windows Version: 10
- Docker for Windows Version: 2.0.0.3 (31259)

**Steps to reproduce the behavior**
- run `docker pull sqlflow/sqlflow:latest`  in  docker

**Comment by wangkuiyi** [comment]
It seems that Docker for Windows has two modes -- Linux container mode and Windows container mode. On Windows 10, the default one is Windows container mode. According to the discussions in the Docker community, a quick solution is switching to Linux mode: https://forums.docker.com/t/docker-for-windows-image-operating-system-linux-cannot-be-used-on-this-platform/28936/3.

Please let us know if that works. If so, it seems a lower priority for SQLFlow project to produce and maintain a Windows Docker image; otherwise, we might have to maintain two images.
