### ISSUE TITLE
Failed running Demo 1 in Quick Start

### ISSUE THREAD

**Issue by hungry1526** [sql-machine-learning/sqlflow#280]
Hi guys,

I am following instructions from Demo 1: https://github.com/sql-machine-learning/sqlflow/blob/develop/doc/quickstart.md#demo-1-jupyter-notebook

During MySQL setup, I had to changeMySQL port to 3307 due to port conflict in my Macbook Pro, in command below:
```
docker run --rm -d --name sqlflowdata \
   -p **3307:3307** \
   -e MYSQL_ROOT_PASSWORD=root \
   -e MYSQL_ROOT_HOST=% \
   sqlflow:data
```

In Demo 1 Step 2, I typed in a correct SQL statement in Jupyter notebook, but it failed in execution in the cell :
```
   %%sqlflow
   select * from iris.train limit 2;
```
with below error message below:

``` 
_Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "channel is in state TRANSIENT_FAILURE"
	debug_error_string = "{"created":"@1555468229.556767000","description":"channel is in state TRANSIENT_FAILURE","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":2294,"grpc_status":14}"
```

I believe that I am strictly following instruction, could anyone take a look? I checked MySQL connection, it was fine. 

Thanks.

**Comment by weiguoz** [comment]
@hungry1526 Can you connect to mysql server by other client?

**Comment by hungry1526** [comment]
Problem solved, changed port mapping at Docker Run -p 3306:3307 etc...

**Comment by hungry1526** [comment]
Thanks @weiguoz and @wangkuiyi for help, appreciate it.

**Comment by weiguoz** [comment]
> Problem solved, changed port mapping at Docker Run -p 3306:3307 etc...

The running port of mysql in the docker is 3306 default

**Comment by wangkuiyi** [comment]
Recording the reason here: we need to change the listening port of MySQL server container and the sending port of SQLFlow server accordingly. 

Sounds an easy fix, however, it exposes a problem: currently, the two commands are in different documents -- the first on in https://github.com/sql-machine-learning/sqlflow/blob/develop/example/datasets/README.md and the second one in 
 https://github.com/sql-machine-learning/sqlflow/blob/develop/doc/quickstart.md. 

Let's make the second document, the Quick Start, self-contained.
