### ISSUE TITLE
Need a "Getting Started" in the document.

### ISSUE THREAD

**Issue by llxxxll** [sql-machine-learning/sqlflow#325]
Need a "Getting Started" in the document.
Users can use SQLFlow by following these steps, complete the training and prediction tasks.

**Comment by hungry1526** [comment]
As discussed offline, we need to have an answer for below Qs:

- Do we prioritize command line or Notebook as the main interface? 

- The backend API for processing queries from Notebook or command line should be the same (from what I understand), how much extra work is needed for porting Notebook to command line or the other way. 

- Do we intend to use docs from Github as true source and build SQLFlow.org on top? If so, should we point developers to SQLFlow.org instead of having two source of docs even though they are the same (content wise)?

**Comment by wangkuiyi** [comment]
Hi @hungry1526 , kindly for your information, the command line client is in its preliminary form, we have been focusing on Jupyter.

I think we will keep documents as Markdown files in the GitHub repository. I agree that we point users to URLs on SQLFlow.org.

**Comment by hungry1526** [comment]
I see, thanks for the clarification.  @wangkuiyi
