### ISSUE TITLE
How to use SQLFlow on top of Spark

### ISSUE THREAD

**Issue by 90217** [sql-machine-learning/sqlflow#344]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered (This is optional)**

**Additional context**

**Comment by llxxxll** [comment]
能否详细描述一下您的需求呢？

**Comment by melin** [comment]
> 能否详细描述一下您的需求呢？

怎么在spark上使用sqlflow，给一个详细文档，怎么结合spark 运行，或者说sqlflow 运行在spark 上，现在大数据分析基本是用spark。

**Comment by llxxxll** [comment]
支持spark的工作目前正在开发中。

**Comment by hungry1526** [comment]
I understand some developers are based in China and prefer using Chinese to create issue, however, we hope SQLFlow to grow into an international open source project with developers coming from all over the world. Could you please create issue in English in the future to follow the convention in our SQLFlow community? Thanks. 

@Bintodo

**Comment by hungry1526** [comment]
Updated title to English

**Comment by wangkuiyi** [comment]
If @melin and @Bintodo were talking about SparkSQL, we have a preliminary idea incorporating it. But it is not yet on our priority list. So, your contribution is welcome.

If you were talking about Spark as a cluster management system, like Kubernetes, I am sorry that we have no plan to run SQLFlow on Spark. Due to the limited number of developers, the only release form we support is Docker images (maybe rkt in the future), and the only cluster management system we will support is Kubernetes.
