### ISSUE TITLE
SQL Select statement failure on CentOS

### ISSUE THREAD

**Issue by msw1535540** [sql-machine-learning/sqlflow#350]
在centos7上使用命令行运行示例：
sqlflow> SELECT *
FROM iris.train
TRAIN DNNClassifier
WITH n_classes = 3, hidden_units = [10, 20]
COLUMN sepal_length, sepal_width, petal_length, petal_width
LABEL class
INTO sqlflow_models.my_dnn_model;

报错：
File "<stdin>", line 34

    feature_columns = [tf.feature_column.(key="sepal_length"),

                                         ^

SyntaxError: invalid syntax

**Comment by hungry1526** [comment]
I am not sure if we support CentOS environment, does anyone know?

**Comment by hungry1526** [comment]
On a side note, I understand some developers following SQLFlow repo are based in China and prefer using Chinese to create the issue, however, we hope SQLFlow to grow into an international open source project with developers coming from all over the world. Could you please create issue in English in the future to follow the convention in our SQLFlow community? Thanks.

@msw1535540

**Comment by hungry1526** [comment]
Updated title to English

**Comment by wangkuiyi** [comment]
I believe it is a great idea to run SQLFlow on CentOS, which is a widely used Linux distro. However, due to our limited engineering resource, at the right moment, we don't have enough developers to support running SQLFlow on native Linux distros like CentOS or Debian. The only way we release SQLFlow is as Docker images.  To run the pre-built images or to build your own from source code, please refer to our documents https://github.com/sql-machine-learning/sqlflow#how-to-use-sqlflow.

We would highly appreciate if someone could contribute and maintain a CentOS package of SQLFLow.
