### ISSUE TITLE
Use independent storage media to save models

### ISSUE THREAD

**Issue by weiguoz** [sql-machine-learning/sqlflow#377]
**Is your feature request related to a problem? Please describe.**

We save models into SQL engines as tables, which :

1. costs user quota in SQL engines, which might be an expensive cloud resource,
2. cannot reuse the model across SQL engines.

Also, each deployment of SQLFlow is configured to connect a certain SQL engine instance, so, if we save a model in Hive, we cannot use MySQL data for prediction using this model.

**Describe the solution you'd like**

Save models in independent storage services bound to the SQLFlow server container.

**Comment by weiguoz** [comment]
Related [comments](https://github.com/sql-machine-learning/sqlflow/pull/319#pullrequestreview-236454187) in #319

**Comment by wangkuiyi** [comment]
I agree that we can save models into the filesystem. I would like to remind that we should write the models into the **local filesystem**, instead of calling the API of some storage services like HDFS or Amazon S3.

I have this suggestion because when we deploy SQLFlow server, we'd deploy it using Kubernetes, and we can configure Kubernetes to bind HDFS directories or S3 directories into the SQLFlow server container as local directories. So when SQLFlow saves models into a local directory, it actually saves to HDFS or S3, without calling HDFS API or S3 API.  This keeps SQLFlow's source code independent with storage services.

During unit testing, the models are saved to the in-container filesystem, and it is just fine.

**Comment by tonyyang-svail** [comment]
@Yancey1989 is working on adding configuration on saving model files in the local fs instead of the database. The current implementation removes the model files using `defer`, please take a look at the following code section.

https://github.com/sql-machine-learning/sqlflow/blob/39466e4a4ce127c59ce5224de578db35da044bd2/sql/executor.go#L209-L220

To support saving models files in the local directory, you may simply put `defer os.RemoveAll(cwd) ` inside a if statement.

**Comment by Yancey0623** [comment]
Thanks for @tonyyang-svail 's reminding, I'm working on this feature, and would add a setup argument of sqlflow-server like `sqlflow-server --mode_dir /mnt/models'.

**Comment by hungry1526** [comment]
In this case, are we using local FS in container as a temporary directory? Do we expect other use case of the saved model in addition to train/pred?

**Comment by ggaaooppeenngg** [comment]
Tensorflow has full FS interface support for HDFS and S3, but K8S PersistentVolume doesn't.
