### ISSUE TITLE
CI failure after merging a PR

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/sqlflow#411]
**Description**

After merging https://github.com/sql-machine-learning/sqlflow/pull/401, the CI status on README.md turned into red. And the CI status of the develop branch (https://travis-ci.org/sql-machine-learning/sqlflow) shows failure. However, the log doesn't show any error; instead, all tests passed.

**Comment by wangkuiyi** [comment]
I went over the full log. All the `docker run` command exits with 0. It seems that everything is alright.

Is the problem due to the use of `set -e` in [`.travis.yml`](https://github.com/sql-machine-learning/sqlflow/blob/370360092f182fd73979d57a1b2e1f591304a249/.travis.yml#L28)? Should we make

https://github.com/sql-machine-learning/sqlflow/blob/370360092f182fd73979d57a1b2e1f591304a249/.travis.yml#L27-L33

a shell script file?

**Comment by typhoonzero** [comment]
This is the same issue of https://github.com/sql-machine-learning/sqlflow/issues/407, I'll merge a quick fix today, and add back coverage then. 

I just need a way to test travis "deploy" stage to upload coverage data, since the travis secret key is only accessible in develop branch build, cannot test using PRs.
