### ISSUE TITLE
Specify the SQLFlow submitter in Session struct

### ISSUE THREAD

**Issue by Yancey0623** [sql-machine-learning/sqlflow#539]
**Is your feature request related to a problem? Please describe.**

Currently, the SQLFlow gRPC server can switch the submitter class by modifying the environment SQLFLOW_submitter:
https://github.com/sql-machine-learning/sqlflow/blob/2b5d0e69c05167b0080a5b99cf45cb33f7f44806/sql/executor.go#L223-L225
but users cannot specify this on the client side(pysqlflow) .

 
**Describe the solution you'd like**

Passing the sqlflow submitter class in the https://github.com/sql-machine-learning/sqlflow/blob/develop/server/proto/sqlflow.proto

**Comment by typhoonzero** [comment]
| submitter | model name | local engine | distributed engine | distributed platform |
| ---------- | ------------ | ------------ | ------------------ | ------------------ |
| codegen_tf | `Estimator`, `models.KerasModel` | tf | - | - |
| codegen_alps | `Estimator`, `path.to.your.custom.model` | tf | ALPS + PAI | yarn/k8s |
| codegen_edl | ?? | ?? | EDL master? | k8s |
| codegen_xgboost | `xgboost.xxx` | ant_xgboost | xgboost launcher | yarn/k8s |

**Comment by tonyyang-svail** [comment]
@Yancey1989 Instead of specifying the SQLFlow submitter in session struct, I would rather prefer determining submitter based on the estimator name. There are two advantages.

(1) The prediction SQL can infer the submitter based on the saved train SQL.
(2) Different clients don't need to reimplement support of switching SQLFlow submitter.

As the model name rule listed by @typhoonzero, we use the model name to determine TF and XgBoost. For different runtime engine of TF (native, ALPS, EDL etc), we hard code them on the server using SQLFlow_submiiter. The hard coding is sufficient because there is usually one TF runtime engine for one deployment.
