### ISSUE TITLE
How to distinguish different models (estimators)?

### ISSUE THREAD

**Issue by sperlingxx** [sql-machine-learning/sqlflow#598]
Sqlflow supports various kinds of models (estimators):  TensorFlow Estimator, Keras, ALPS, XGBoost (up coming). How can we distinguish one from another?

For now, we distinguish `keras model` from `tf estimator model` via _ModelURI_.
```go
// parseModelURI returns isKerasModel, modelClassString
func parseModelURI(modelString string) (bool, string) {
	if strings.HasPrefix(modelString, "sqlflow_models.") {
		return true, modelString
	}
	return false, fmt.Sprintf("tf.estimator.%s", modelString)
}
```

This issue is related to PR #595

**Comment by wangkuiyi** [comment]
I am not sure I understand the question well. I have no context about the concept of ModelURI.

I don't think SQLFlow need to distinguish the model representations -- Estimator vs. Keras vs. xgboost. The SQLFlow syntax is like 

```sql
SELECT ... TO TRAIN model_name ...
```

and 

```sql
SELECT ... TO PREDICT model_name ...
```

Where `model_name` is an identifier, which could be the name of a Python class derived from `tf.Estimator` or `tf.keras.Model`.

It is the code generator which determines what the `model_name` must be. Alps code generator `codegen_alps.go` assumes that `model_name` names an Estimator-derived class, because it generates Python programs that call the Alps system to train/predict Estimator models.

ElasticDL, similar to the Alps system, is an execution engine of TensorFlow models. It accepts that `model_name` names a Keras class, Estimator class, or a function that calls Keras functional API to define models.

Authors of Alps told me that they plan to manage model zoo by putting Python classes that define models on a Git repo. In that way, we could refer to each Python class by a URI. I am not sure if this is also the idea you want to maintain an xgboost model zoo?

ElasticDL's high-level API `elastic.train(model_name, ...` packs the model zoo that contains the `model_name` into a Docker image before filing a distributed job on Kubernetes clusters to run this image. With ElasticDL, there seem no concepts like model URI.

Hope the information is useful for your contribution to the xgboost code generator. Thanks!

**Comment by sperlingxx** [comment]
@wangkuiyi Thanks for comprehensive comment, I will close this issue and PR #595. And xgboost code generator will be an independent module as `codegen_ALPS`.
