### ISSUE TITLE
Support for batch entry of feature names in COLUMN handles

### ISSUE THREAD

**Issue by Echo9573** [sql-machine-learning/sqlflow#636]
How to implement batch input of feature names in COLUMN handles？For example, there are currently 100 features. Can you select all features directly? Or set an exclusion, that is, do not select one or more features?

**Comment by tonyyang-svail** [comment]
~~@Echo9573 Thanks for submitting this issue. You are right, SQLFlow should be able to support selecting a batch of column names. One solution could be implementing `COLUMN *`.~~

~~Consider we want to train a tree model on the following table with v1, v2, ..., v29 as the features and class as the label.~~

<table>
  <tr>
    <th colspan="5">my_table</th>
  </tr>
  <tr>
    <td>v1</td>
    <td>v2</td>
    <td>...</td>
    <td>v16</td>
    <td>class</td>
  </tr>
  <tr>
    <td>1.2</td>
    <td>3.9</td>
    <td>...</td>
    <td>-2.4</td>
    <td>1</td>
  </tr>
  <tr>
    <td>...</td>
    <td>...</td>
    <td>...</td>
    <td>...</td>
    <td>...</td>
  </tr>
</table>

Instead of writing

```SQL
SELECT * FROM my_table
TRAIN XGBoostEstimator
WITH ...
COLUMN v1,v2,v3,v4,v5,v6,v7,v8,v9,v10,v11,v12,v13,v14,v15,v16
LABEL class
```

~~We can implement syntax support for `COLUMN *` which has the same effect as `COLUMN v1,v2,v3,v4,v5,v6,v7,v8,v9,v10,v11,v12,v13,v14,v15,v16`. Please be aware that `COLUMN *` doesn't include the `class` field because it is used in `LABEL`. How do you like the syntax?~~

**Comment by tonyyang-svail** [comment]
@Echo9573 Thanks for submitting this issue. In the next couples weeks, we will be implementing feature derivation. Where,

> [We assume all the selected columns will be used as either COLUMN or LABEL.](https://github.com/sql-machine-learning/sqlflow/blob/develop/doc/design/design_feature_derivation.md#simpler-column-clause)

So we can write

```SQL
SELECT * FROM my_table
TRAIN XGBoostEstimator
WITH ...
LABEL class
INTO my_model_table;
```

**Comment by tonyyang-svail** [comment]
@typhoonzero Please make sure there is a test covering this case.

**Comment by typhoonzero** [comment]
Sure.

**Comment by typhoonzero** [comment]
Tests added in https://github.com/sql-machine-learning/sqlflow/blob/develop/go/cmd/sqlflowserver/e2e_common_cases.go
