### ISSUE TITLE
Support SQL program with comments

### ISSUE THREAD

**Issue by typhoonzero** [sql-machine-learning/sqlflow#904]
Need to support SQL program with comments like:

```SQL
-- Create tmp table for training
CREATE TABLE tmp_train AS SELECT * FROM origin_table;
-- Start training
SELECT * FROM tmp_train
TRAIN DNNClassifier
WITH n_classes=2
COLUMN a,b,c
INTO somemodel;
```

**Comment by tonyyang-svail** [comment]
@typhoonzero We definitely need this feature. The lexer should be responsible for ignoring comments. For example, in flex, this feature can be implemented fairly easily. [ref](https://stackoverflow.com/questions/25395251/detecting-and-skipping-line-comments-with-flex)

Also, the lexer can ignore `;` in the comment, so that dividing multiple SQL statements based on `;`  token won't be affected.

**Comment by tonyyang-svail** [comment]
A helpful explanation on commenting: https://www.techonthenet.com/sql/comments.php

Implementation reference from TiDB: https://github.com/pingcap/parser/blob/51a2e3b2e34b61a7519e7d3e17dac38f0e8684f7/lexer.go#L361-L452

Robs talk on Lexer: https://www.youtube.com/watch?v=HxaD_trXwRE

**Comment by typhoonzero** [comment]
Feature already supported in the parser. Comments are removed in the parser result.
